name: Release document to GitHub Pages
description: Release document to GitHub Pages
author: Shunsuke Suzuki
branding:
  icon: git-commit
  color: blue
inputs:
  publish_branch:
    description: A target branch for deployment
    required: false
    default: gh-pages
  source_dir:
    description: A source directory. Commands like npm run build will be executed in this directory
    required: false
    default: ${{github.workspace}}
  publish_dir:
    description: A directory to publish the built files
    required: false
    default: 'public'
  destination_dir:
    description: A destination subdirectory for deployment
    required: false
    default: ''
  repository:
    description: An external repository (owner/repo).
    required: false
    default: ${{ github.repository }}
  issue_number:
    description: Issue to number to notify the failure
    required: false
runs:
  using: composite
  steps:
    - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
      with:
        repository: ${{ inputs.repository }}
        persist-credentials: false
    - uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
      with:
        node-version: '22'
        cache: 'npm'
        cache-dependency-path: ${{ inputs.source_dir }}/package-lock.json
    - run: npm ci
      working-directory: ${{ inputs.source_dir }}
      shell: bash
    - run: npm run build
      working-directory: ${{ inputs.source_dir }}
      shell: bash

    - uses: suzuki-shunsuke/gh-pages-action@5df123b4f8ae31edbe71bcc9a28a9598c29b1011 # v0.0.6
      if: github.event_name != 'pull_request'
      with:
        publish_dir: ${{ inputs.publish_dir }}
        destination_dir: ${{ inputs.destination_dir }}

    - uses: suzuki-shunsuke/notify-workflow-error-action@e5e8817e62eb122231d162dbc8309c4d05a21b2e # v0.1.0
      if: always() && inputs.issue_number != '' && github.event_name != 'pull_request'
      with:
        issue_number: ${{ inputs.issue_number }}
        status: ${{ github.action_status }}
